vim.api.nvim_create_user_command("OdinBuild", function()
	vim.cmd("enew")
	vim.cmd("term odin build . -debug")
end, {})

vim.api.nvim_create_user_command("OdinBuildFile", function()
    local filepath = vim.api.nvim_buf_get_name(0)
    local filename = vim.fn.fnamemodify(filepath, ':t')
	vim.cmd("enew")
	vim.cmd("term odin build " .. filename .. " -debug -file")
end, {})

vim.api.nvim_create_user_command("OdinRun", function()
	vim.cmd("enew")
	vim.cmd("term odin run . -debug")
end, {})

vim.api.nvim_create_user_command("OdinRunFile", function()
    local filepath = vim.api.nvim_buf_get_name(0)
    local filename = vim.fn.fnamemodify(filepath, ':t')
	vim.cmd("enew")
	vim.cmd("term odin run " .. filename .. " -debug -file")
end, {})

vim.api.nvim_create_user_command("OdinTest", function()
	vim.cmd("enew")
	vim.cmd("term odin test .")
end, {})
